gameReviewProject/gameReviewApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webApp.urls'))
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gameReviewProject/webApp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# Found login tutorial https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html
urlpatterns = [
    path('', views.all_reviews, name='all_reviews'),
    path('make_review', views.make_review, name='make_review'),
    path(r'^signup/$', views.signup, name='signup'),
    path('search_video', views.search_video, name='search_video'),
    path('blank_new_review', views.blank_new_review, name='blank_new_review'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='webApp/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='webApp/all_reviews.html'), name='logout'),
    path('accounts/profile/', views.my_reviews, name='my_reviews')
]

gameReviewProject/webApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

class Review(models.Model):
    user = models.ForeignKey('auth.User', null=False, on_delete=models.CASCADE)
    game_name = models.CharField(max_length=200, null=False)
    game_summary = models.TextField(blank=True, null=False)
    reviewers_opinion = models.TextField(blank=True, null=False)
    # Found validators on stack overflow
    rating = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(10), MinValueValidator(1)], null=False)
    photo = models.ImageField(upload_to='user_images/', blank=True, null=True)
    video_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        photo_str = self.photo if self.photo else 'no photo'
        return f'{self.pk}: {self.game_name} {self.game_summary} {self.reviewers_opinion} {self.rating} {photo_str} {self.video_id}'


# This model is used to get the user's search and implement the search
class Search(models.Model):
    user = models.ForeignKey('auth.User', null=False, on_delete=models.CASCADE)
    video_search = models.CharField(max_length=200, null=True)
    created_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.video_search}'

gameReviewProject/webApp/forms.py
from django import forms
from django.forms import FileInput, ValidationError
from .models import Review, Search

class NewReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('game_name', 'game_summary', 'reviewers_opinion', 'rating', 'photo', 'video_id')

    # Clean the rating input from the user so they only enter a number 1 - 10
    def clean_rating(self):
        # set rating variable to the user's input
        rating = self.cleaned_data['rating']

        if rating < 1 or rating > 10:
            raise ValidationError('Please enter a rating 1-10')

        return rating



class NewSearchForm(forms.ModelForm):
    class Meta:
        model = Search
        fields = ('video_search',)

gameReviewProject/webApp/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .forms import NewReviewForm, NewSearchForm
from .models import Review, Search
from .youtube_api import main


# When the '' url is entered into the browser this method is called.
# This method will render the home.html template
# This method is not used in the running app, it was a placeholder during development
def home(request):
    return render(request, 'webApp/home.html')



# Render make_review.html with two blank forms
@login_required
def blank_new_review(request):
    new_review_form = NewReviewForm()
    new_search_form = NewSearchForm()
    return render(request, 'webApp/make_review.html', {'new_review_form': new_review_form, 'new_search_form': new_search_form})



@login_required
def make_review(request):   
    # If the request is a POST than take the information given from the user in the form
    # The request should always be a POST because there is no button associated with this link that is not a POST
    if request.method == 'POST':
        # Creates a form instance and populate the data with what the user provided
        new_review_form = NewReviewForm(request.POST, request.FILES)
        # Blank video search form for rendering if the form validation fails
        new_search_form = NewSearchForm()
        # don't save the form yet until the user is verified
        #review = form.save(commit=False)
        # Assign the user
        #review.user = request.user
        # Save the form
        if new_review_form.is_valid():
            review = new_review_form.save(commit=False)
            review.user = request.user
            review.save()
            # after the form is saved reload the make review page
            return redirect('my_reviews')
        else:
            return render(request, 'webApp/make_review.html', {'new_review_form': new_review_form, 'new_search_form': new_search_form})

    #This code should never be reached, leaving for reference
    #video_ids = main()
    # If the request is not a POST request than render a blank form
    #new_review_form = NewReviewForm()
    # send the new review form as a variable that can be used in the makereview.html template
    #return render(request, 'webApp/make_review.html', {'new_review_form': new_review_form, 'video_ids': video_ids})



@login_required
def search_video(request):
    # If the method is a POST request than take the information from the user to search for YouTub videos
    # This will always be POST as their are no buttons leading to this method without POST
    if request.method == 'POST':
        # Create a form instance for the new_review_form in order to save the user's data so they don't re-enter it
        new_review_form = NewReviewForm()
        # Get the user's entry into the YouTube video search form
        new_search_form = NewSearchForm(request.POST)
        print(new_search_form)
        if new_search_form.is_valid():
            search = new_search_form.save(commit=False)
            search.user = request.user
            search.save()
            print(Search.objects.all())
            video_ids = main()
            return render(request, 'webApp/make_review.html', {'new_review_form': new_review_form, 'new_search_form': new_search_form, 'video_ids': video_ids})
        else:
            video_ids = []
            return render(request, 'webApp/make_review.html', {'new_review_form': new_review_form, 'new_search_form': new_search_form, 'video_ids': video_ids})



def all_reviews(request):
    # Gets all Review objects from the database
    reviews = Review.objects.all().order_by('game_name')
    # Sends all review objects to be rendered on all_reviews.html
    return render(request, 'webApp/all_reviews.html', {'reviews': reviews})



@login_required
def my_reviews(request):
    my_reviews = Review.objects.filter(user=request.user)
    return render(request, 'webApp/my_reviews.html', {'my_reviews': my_reviews})



# Found signup tutorial https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html
def signup(request):
    if request.method == 'POST':
        user_creation_form = UserCreationForm(request.POST)
        if user_creation_form.is_valid():
            user_creation_form.save()
            username = user_creation_form.cleaned_data.get('username')
            raw_password = user_creation_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('all_reviews')
    else:
        user_creation_form = UserCreationForm()
    return render(request, 'webApp/signup.html', {'user_creation_form': user_creation_form})

gameReviewProject/webApp/templates/home.htm
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Solid Game Reviews</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">
    </head>

    <body>

    </body>
</html>

gameReviewProject/webApp/templates/webApp/all_reviews.html
{% extends 'webApp/home.html' %}
{% block content %}



{% if reviews %}

    {% for review in reviews %}
        <div class="container">
            {% if review.photo %}
                <div class='row'>
                    <div class='col'><img class="photo-styling" src="{{ review.photo.url }}"></div>
                </div>
            {% else %}
                <div class='row'>
                    <div class='col-6'>No photo available.</div>
                </div>
            {% endif %}

            <div class="row">
                <div class="col-6 center-text"><h3>Game: {{ review.game_name }}</h3></div>
                <div class="col-6 center-text"><h3>Rating: {{ review.rating }}</h3></div>
            </div>

            <div class="row">
                <div class="col-6"><h5>Game Summary: </h5></div>
                <div class='col-6'><h5>Personal Opinion: </h5></div>
            </div>

            <div class="row">
                <div class="col-6">{{ review.game_summary }}</div>
                <div class='col-6'>{{ review.reviewers_opinion }}</div>
            </div>

            {% if review.video_id %}
                <div class='row'>
                    <div class='col center-text'>
                        <iframe align='middle' width='420' height='315' src="https://www.youtube.com/embed/{{ review.video_id }}"></iframe>
                    </div>
                </div>
            {% else %}
                <div class='row'>
                    <div class='col'>
                        No video available.    
                    </div>
                </div>
            {% endif %}
        </div>
    {% endfor %}

{% else %}

    <div class="row">
        <div class="col center-text">There are no reviews in the database.</div>
    </div>

{% endif %}



{% endblock %}

gameReviewProject/webApp/templates/webApp/home.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <title>Solid Video Game Reviews</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">
        <link rel='stylesheet' href="{% static 'css/make_review.css' %}" type='text/css'>
        <link rel='stylesheet' href="{% static 'css/all_reviews.css' %}" type='text/css'>
    </head>

    
    <body>

        <div class='jumbotron'>
            <div class='row align-items-center'>
                <div class='col'><h1>Solid Video Game Reviews</h1></div>
                <div class='col-1 center-text'><a class="btn btn-outline-secondary" href="{% url 'all_reviews' %}" role="button">All Reviews</a></div>
                <div class='col-1 center-text'><a class="btn btn-outline-secondary" href="{% url 'blank_new_review' %}" role="button">Make Reviews</a></div>
                {% if user.is_authenticated %}
                    <div class='col-1 center-text'><a class="btn btn-outline-success" href="{% url 'my_reviews' %}" role="button">{{ user.username }}</a></div>
                    <div class='col-1 center-text'><a class="btn btn-outline-danger" href="{% url 'logout' %}" role="button">Logout</a></div>
                {% else %}
                    <div class='col-1 center-text'><a class="btn btn-outline-primary" href="{% url 'signup' %}" role="button">Sign Up</a></div>
                    <div class='col-1 center-text'><a class="btn btn-outline-success" href="{% url 'login' %}" role="button">Login</a></div>
                {% endif %}
            </div>
        </div>


        {% block content %}
        {% endblock %}

    </body>

</html>

gameReviewProject/webApp/templates/webApp/login.html
{% extends 'webApp/home.html' %}
{% block content %}

<div class='container'>
    <form method='POST' action=''>
        {% csrf_token %}
        <table id='login_form'>
            {{ form.as_table }}
        </table>
        <button type='submit'>Login</button>
    </form>
</div>

{% endblock %}

gameReviewProject/webApp/templates/webApp/make_review.html
{% extends 'webApp/home.html' %}
{% comment %} Found cripsy forms tutorial https://simpleisbetterthancomplex.com/tutorial/2018/08/13/how-to-use-bootstrap-4-forms-with-django.html {% endcomment %}
{% load crispy_forms_tags %}
{% block content %}

{% comment %} If the user enters a number outside of the rating range 1-10 this error message should appear {% endcomment %}

{% comment %} Load the make review form with crispy bootstrap css {% endcomment %}
<div class='container'>
    <div class='row'>
        <div class='col center-text container'>
            <form method="POST" action="{% url 'make_review' %}" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="row">
                    <div class="col-6">{{ new_review_form.game_name|as_crispy_field }}</div>

                    <div class="col-6">{{ new_review_form.rating|as_crispy_field }}</div>
                </div>

                {{ new_review_form.game_summary|as_crispy_field }}
                {{ new_review_form.reviewers_opinion|as_crispy_field }}
                
                <div class='row align-items-center'>
                    <div class='col-4'>Add the game's cover photo!</div>
                    <div class='col-4'>{{ new_review_form.photo }}</div>
                    <div class='col-4'><button id="add-new-review" type="submit" class="btn btn-success">Add</button></div>
                </div>

                <div class='row align-items-center'>
                    <div class='col-4 center-text'>{{ new_review_form.video_id|as_crispy_field }}</div>
                </div>

            </form>
        </div>
    </div>
</div>

{% comment %} Make a form for searching Youtube videos {% endcomment %}
<div class='container'>
    <div class='row'>
        <div class='col'>
            <form method="POST" action="{% url 'search_video' %}">
                {% csrf_token %}
                {{ new_search_form|crispy }}
                <button id="new-video-search" type="submit" class="btn btn-success">Search</button>
            </form>
        </div>
    </div>
</div>

{% comment %} Found iframe on w3school.com {% endcomment %}
{% comment %} For each video that is returned from the API video list put that video into a container {% endcomment %}
{% if video_ids %}
    {% for video_id in video_ids %}
        <div class='container center-text'>
            <p data-video-id="{{ video_id }}" class="youtube-video-id">Click here to select this video!</p>
            <iframe align='middle' width='420' height='315' src="https://www.youtube.com/embed/{{ video_id }}"></iframe>
        </div>
    {% endfor %}
{% else %}
        <div class='container center-text'>
            <p>No videos were returned</p>
        </div>
{% endif %}


<script>

let reviewFormSubmit = document.querySelector('#add-new-review')
let videoFormSubmit = document.querySelector('#new-video-search')
let videoIdTextInput = document.querySelector('#id_video_id')

// An addition would be to disable submit buttons until everything is 

reviewFormSubmit.addEventListener('click', function(event) {
    if (!videoFormCompleted()) {
        event.preventDefault()  // prevent form submit 
    }
})

document.querySelectorAll('.youtube-video-id').forEach( videoIdElement => {
    videoIdElement.addEventListener('click', function() {
        videoIdTextInput.value = this.dataset.videoId   // data-video-id with no data- and in camelCase 
    })
})

function videoFormCompleted() {
    // What's your opinion on this way of deciding if a video search has been made? 
    // checks if there is anything in the video ID text input
    return !!videoIdTextInput.value.trim()  // not not returns false if string is empty, true otherwise 
}






</script>


{% endblock %}

gameReviewProject/webApp/templates/webApp/my_reviews.html
{% extends 'webApp/home.html' %}
{% block content %}



{% if my_reviews %}

    {% for review in my_reviews %}
        <div class="container">
            <div class="row">
                <div class="col-6"><h3>Game: {{ review.game_name }}</h3></div>
                <div class="col-6"><h3>Rating: {{ review.rating }}</h3></div>
            </div>

            <div class="row">
                <div class="col-6">Game Summary: </div>
                <div class="col-6">{{ review.game_summary }}</div>
            </div>

            <div class="row">
                <div class='col-6'>Reviewer Notes: </div>
                <div class='col-6'>{{ review.notes }}</div>
            </div>

            {% if review.photo %}
                <div class='row'>
                    <div class='col-6'>Cover Photo: </div>
                    <div class='col'><img class="photo-styling" src="{{ review.photo.url }}"></div>
                </div>
            {% else %}
                <div class='row'>
                    <div class='col-6'>Cover Photo: </div>
                    <div class='col-6'>No photo available.</div>
                </div>
            {% endif %}
        </div>
    {% endfor %}

{% else %}

    <div class="row">
        <div class="col center-text">You have not made any reviews.</div>
    </div>

{% endif %}



{% endblock %}

gameReviewProject/webApp/templates/webApp/signup.html
{% extends 'webApp/home.html' %}
{% block content %}

<div class='container'>
    <form method='POST' action="{% url 'signup' %}">
        {% csrf_token %}
        {{ user_creation_form }}
        <button id="sign-up" type="submit" class="btn btn-success">Sign Up</button>
    </form>
</div>

{% endblock %}